name = "chatbot-ai"
main = "src/index.js"
compatibility_date = "2026-04-17"
account_id = "84cbacc4816c29c294101ec57a0bea5d"

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1
