name = "ai-kb"
main = "src/index.js"
compatibility_date = "2026-04-17"
account_id = "84cbacc4816c29c294101ec57a0bea5d"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "baza"
database_id = "11a157a7-c3e0-4b6b-aa24-3026992db298"

[[r2_buckets]]
binding = "CATALOG"
bucket_name = "vedro"

[assets]
directory = "./public"
binding = "ASSETS"

# Cron: запуск D1 → R2 каждый день в 03:00 UTC
[triggers]
crons = ["0 3 * * *"]

[observability]
enabled = true
head_sampling_rate = 1

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  persist = true
  invocation_logs = true

  [observability.traces]
  enabled = false
  persist = true
  head_sampling_rate = 1