name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Upload catalog.gz to R2
        run: npx wrangler r2 object put vedro/catalog.gz --file=data/catalog.gz --content-type=application/gzip
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: 84cbacc4816c29c294101ec57a0bea5d

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 84cbacc4816c29c294101ec57a0bea5d
